vich_uploader:
    db_driver: orm

    mappings:

        tricks_image:
            uri_prefix: /uploads/tricks
            upload_destination: '%kernel.project_dir%/public/uploads/tricks'

            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true

